#!/bin/bash

NFS_MOUNTS=$(compgen -A variable|grep MOUNT_)

rpcbind --

for mount in $NFS_MOUNTS
do
  index=${mount##*_}

  server="${mount}_SERVER"
  if [ "${!server}" == "" ]; then server="SERVER"; fi

  options="${mount}_OPTIONS"
  if [ "${!options}" == "" ]; then options="OPTIONS"; fi

  if [ ${!mount} == $COMMON* ]
  then
    source=${!mount}
    target=${TARGET}${!mount#$COMMON}
  else
    source=${COMMON}${!mount}
    target=${TARGET}${!mount}
  fi

  if [[ -n ${!mount} ]] ; then
    mkdir -p $target &&
    mount -t nfs -o ${!options} ${!server}:${source} ${target} &&
    echo "Mounted ${!server}:${source} to ${target} (${!options})"
  fi
done

while true; do sleep 1000; done
