#!/bin/bash

NFS_MOUNTS=$(compgen -A variable|grep MOUNT_)

rpc.statd & rpcbind --

for mount in $NFS_MOUNTS
do
  index=${mount##*_}

  if [[ $mount == *"_SERVER" ]] || [[ $mount == *"_OPTIONS" ]] || [[ $mount == *"_TARGET" ]]; then continue; fi

  server="${mount}_SERVER"
  if [ "${!server}" == "" ]; then server="SERVER"; fi

  options="${mount}_OPTIONS"
  if [ "${!options}" == "" ]; then options="OPTIONS"; fi

  target="${mount}_TARGET"
  target="${!target}"
  if [ "${target}" == "" ]; then
    if [ "${!mount}" == "$COMMON"* ]
    then
      source=${!mount}
      target=${TARGET}${!mount#$COMMON}
    else
      source=${COMMON}${!mount}
      target=${TARGET}${!mount}
    fi
  elif [ "${!mount}" == "$COMMON"* ]; then
    source=${!mount}
  else
    source=${COMMON}${!mount}
  fi

  if [[ -n ${!mount} ]] ; then
    if [ -d $target ] && [ -n "$(ls -A $target)" ]; then
      echo "$(date '+%m-%d-%Y %H:%M:%S') mount: mounting ${!server}:${source} on ${target} failed: Target already exists and is not empty"
    else
      check=$(mount | grep " on ${target} type " | awk '{print $1;}')
      if [ "$check" != "" ]; then
        echo "$(date '+%m-%d-%Y %H:%M:%S') mount: mounting ${!server}:${source} on ${target} failed: Already mounted to $check"
      else
        mkdir -p $target &&
        echo "${!server}:${source} ${target} nfs ${!options} 0 0" >> /etc/fstab &&
        while read -r line; do
          if [[ $line == "mount"* ]]; then
            echo "$(date '+%m-%d-%Y %H:%M:%S') $line"
          fi
        done < <(mount ${target} 2>&1)

        check=$(mount | grep "${!server}:${source} on ${target}" | awk '{print $NF}')
        if [ "$check" != "" ]; then
          echo "$(date '+%m-%d-%Y %H:%M:%S') mount: mounting ${!server}:${source} on ${target} success: $check"
        fi
      fi
    fi
  fi
done

lighttpd -D -f /etc/lighttpd/lighttpd.conf

#while true; do sleep 1000; done
